
image:
  repo: raspberrypi.local:5000
  name: real_estate
  tag: arm
  digest: "@sha256:d75be328cd0a50a5cb0ba682d4e7f96affba375054fb4250335d5e1f4feae373"

cron_schedule: "0 */12 * * *"

prometheus:
  service:
    retention: "5y"
  server:
    extraFlags:
      - web.enable-lifecycle
      - web.enable-admin-api
