---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: real-estate
spec:
  startingDeadlineSeconds: 10
  schedule: {{ .Values.cron_schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: poller
            image: {{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}{{ .Values.image.digest }}
            env:
              - name: PROMETHEUS_FQDN
                value: http://real-estate-prometheus-pushgateway.{{ .Release.Namespace }}.svc:9091
              - name: PAGES
                value: "{{ .Values.pages }}"
            resources:
              limits:
                cpu: 1000m
                memory: 1024Mi
          restartPolicy: OnFailure
